### ISSUE TITLE
Hola. Asignación 3

### ISSUE THREAD

**Issue by BidelkisCastillo** [biogeografia-201902/unidad-0-asignacion-3-mi-primer-rmd-BidelkisCastillo#1]
Hola. @geofis  No he podido hacer nada, se me ha complicado.
No creo que lo pueda hacer.
Necesito ayuda, repito lo mismo y no me aparece la opción Chunk Output in Console.
Y nada, nada, nada.................................................................................................

**Comment by geofis** [comment]
OK, sería necesario que colocaras aquí en el *issue* los pasos que has dado y qué problema (el primero mejor) tienes. Si tienes un mensaje de error, genial, o una captura de pantalla. Así podría ayudarte.

**Comment by geofis** [comment]
@BidelkisCastillo, clona tu repo de nuevo, haz lo que se pide en las distintas tareas y verifica si ahora obtienes resultados.

**Comment by geofis** [comment]
@BidelkisCastillo, visto que ya resolviste, supongo que puedo cerrar este *issue*
